classDiagram
    class Biblioteka {
        -string nazwa
        -Ksiazka[] ksiazki
        +DodajKsiazke(Ksiazka)
        +ZnajdzKsiazke(string) Ksiazka
    }
    
    class Ksiazka {
        -string tytul
        -string autor
        -string ISBN
        -bool dostepna
        +PrzypiszCzytelnikowi(Czytelnik)
        +ZwrocOdCzytelnika()
    }
    
    class Czytelnik {
        -string imie
        -string nazwisko
        -int idCzytelnika
        -Ksiazka[] wypozyczone
        +WypozyczKsiazke(Ksiazka)
        +ZwrocKsiazke(Ksiazka)
    }
    
    Biblioteka "1" o-- "*" Ksiazka : zawiera
    Czytelnik "*" --> "*" Ksiazka : wypożycza
